language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t keilla/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true keilla/docker-react yarn test -- --coverage
